#pragma config(Motor,  port5,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           backMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           leftMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal);
void rotate(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal);
void strafe(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal);
float deadband(float value, float deadband);
float limit(float value, float limit);

int DEADBAND = 20;
int LIMIT = 127;

task main()
{
	while (true) {
		float leftMotorVal = 0, rightMotorVal = 0, backMotorVal = 0;

		float moveVal = vexRT[Ch3];
		moveVal = deadband(moveVal, DEADBAND);
		move(moveVal, &leftMotorVal, &rightMotorVal, &backMotorVal);

		float rotateVal = vexRT[Ch1];
		rotateVal = deadband(rotateVal, DEADBAND);
		rotate(rotateVal, &leftMotorVal, &rightMotorVal, &backMotorVal);

		float strafeVal = vexRT[Ch4];
		strafeVal = deadband(strafeVal, DEADBAND);
		//strafe(strafeVal, &leftMotorVal, &rightMotorVal, &backMotorVal);

		leftMotorVal = limit(leftMotorVal, LIMIT);
		rightMotorVal = limit(rightMotorVal, LIMIT);
		backMotorVal = limit(backMotorVal, LIMIT);

		motor[leftMotor] = leftMotorVal;
		motor[rightMotor] = rightMotorVal;
		motor[backMotor] = backMotorVal;
	}
}

void move(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal) {
	*leftMotorVal += value;
	*rightMotorVal -= value;
}

void rotate(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal) {
	*leftMotorVal += value;
	*rightMotorVal += value;
	*backMotorVal += value;
}

void strafe(float value, float *leftMotorVal, float *rightMotorVal, float *backMotorVal) {
	*leftMotorVal += value;
	*rightMotorVal += value;
	*backMotorVal -= value;
}

float deadband(float value, float deadband) {
	if (value >= -deadband && value <= deadband) {
		return 0;
	}

	return value;
}

float limit(float value, float limit) {
	if (value > limit) {
		return limit;
	}

	if (value < -limit) {
		return -limit;
	}

	return value;
}
